language: node_js
version: 1.0
sudo: false
node_js:
  - 10
before_script:
  - npm run build
install:
  - npm ci
stages:
  - test
jobs:
  include:
    - stage: test
      script: npm run check:types
      script: npm run lint
      script: npm run test
notifications:
  email:
    on_success: change
    on_failure: always
